M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date 21.11.2024 (чт) 15:07:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-21T15:07:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.300
%
G90
G05
T1
X3.5Y26.5
X3.5Y3.5
X26.5Y26.5
X26.5Y3.5
M30
